spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_campus
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: trace

server:
  port: 8081

cloud-campus:
  security:
    secret: classpath:certs/publicKey.pem
    secret-private: classpath:certs/privateKey.pem
    expireMs: 86400000